//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CoffeeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public int PaymentTypeID { get; set; }
        public int TotalPrice { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
